version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: pgpbot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=30m
    # GPU support (comment out if no GPU available)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pgpbot-api
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - MODEL_NAME=phi3:mini
      - MAX_WORKERS=3
      - RATE_LIMIT=5
      - REDIS_HOST=redis
    volumes:
      - ./backend:/app
      - api_cache:/app/cache
    depends_on:
      redis:
        condition: service_started
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: pgpbot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pgpbot-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: pgpbot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - api
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
  api_cache:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: pgpbot-network 